sudo: false
language: node_js
node_js:
  - "stable"
addons:
    code_climate:
        repo_token: 5dd1089105c5646ecd492907f8224b0ae64890d4befb4bbd9ebbeba55b5acb38
cache:
  directories:
    - node_modules
before_script:
  - npm install -g grunt-cli codeclimate-test-reporter
script:
  - grunt build
  - grunt test_and_coverage
  - codeclimate-test-reporter < coverage/lcov.info
